language: dart

dart:
- stable
- dev

os:
- linux
- osx
- windows

dart_task: test

before_install:
- if [[ "$TRAVIS_OS_NAME" = windows ]]; then
    choco install nodejs.install;
    export PATH="$PATH:/c/Program Files/nodejs";
  fi
- git config --global user.email "travis@local"
- git config --global user.name "Travis CI"

matrix:
  include:
  - name: code formatting
    dart: stable
    dart_task: {dartfmt: --fix}
    os: linux
  - name: static analysis
    dart: stable
    dart_task: {dartanalyzer: --fatal-warnings --fatal-infos .}
    os: linux

branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
