name: CI
on:
  push: {branches: [main]}
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Static analysis (Code)

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with: {persist-credentials: false}
    - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1
    - run: dart --version
    - run: dart pub get
    - run: dart analyze --fatal-infos --fatal-warnings .

  analyze_ci:
    name: Static analysis (GitHub Actions)
    runs-on: ubuntu-latest

    permissions:
      security-events: write # Required by upload-sarif
      actions: read # Required by upload-sarif
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with: {persist-credentials: false}
    - uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
      with: {persona: pedantic}

  test:
    name: "Tests | Dart ${{ matrix.dart-channel }} | ${{ matrix.os }} | shard ${{ matrix.shard }}"

    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        dart-channel: [stable]
        # TODO(nweiz): Re-enable this when
        # https://github.com/dart-lang/sdk/issues/52121#issuecomment-1728534228
        # is addressed.
        # dart-channel: [stable, dev]
        shard: [0, 1, 2]
      fail-fast: false

    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with: {persist-credentials: false}
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
    - run: node --version

    - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1
      with:
        sdk: ${{ matrix.dart-channel }}
    - run: dart --version

    - name: Configure Git
      run: |
        git config --global user.email "ci@local"
        git config --global user.name CI

    - run: dart pub get
    - run: dart run test -r expanded --total-shards 3 --shard-index "$SHARD"
      shell: bash
      env:
        SHARD: ${{ matrix.shard }}

  browser-test:
    name: "Browser Tests | Dart ${{ matrix.dart-channel }}"

    strategy:
      matrix:
        dart-channel: [stable]
        # TODO(nweiz): Re-enable this when
        # https://github.com/dart-lang/sdk/issues/52121#issuecomment-1728534228
        # is addressed.
        # dart-channel: [stable, dev]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
    - uses: browser-actions/setup-chrome@2e1d749697dd1612b833dba4a722266286fbefcd # v2
      id: setup-chrome
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with: {persist-credentials: false}
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
    - run: node --version

    - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1
      with:
        sdk: ${{ matrix.dart-channel }}
    - run: dart --version

    - name: Configure Git
      run: |
        git config --global user.email "ci@local"
        git config --global user.name CI

    - run: dart pub get
      working-directory: ./browser_library_test

    - run: dart run grinder before-test
      working-directory: ./browser_library_test

    # Run browser tests on macos to avoid "No usable sandbox!" error on linux.
    # See https://github.com/puppeteer/puppeteer/issues/12818
    # Ubuntu 23+ doesn't like running puppeteer without disabling AppArmor.
    - name: Disable AppArmor
      run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

    - run: '"$CHROME_EXECUTABLE" --version'
      env:
        CHROME_EXECUTABLE: ${{ steps.setup-chrome.outputs.chrome-path }}

    - run: dart run test --platform chrome --exclude-tags not-on-gh-actions
      working-directory: ./browser_library_test
      env:
        CHROME_EXECUTABLE: ${{ steps.setup-chrome.outputs.chrome-path }}

  format:
    name: "Code formatting"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with: {persist-credentials: false}
    - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1
    - run: dart --version
    - run: dart pub get
    - run: dart fix --apply
    - run: dart format .
    - run: git diff --exit-code
