name: CI
on:
  push: {branches: [main]}
  pull_request:

jobs:
  analyze:
    name: "Static analysis"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1.2
    - run: dart --version
    - run: dart pub get
    - run: dart analyze --fatal-infos --fatal-warnings .

  test:
    name: "Tests | Dart ${{ matrix.dart-channel }} | ${{ matrix.os }} | shard ${{ matrix.shard }}"

    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        dart-channel: [stable]
        # TODO(nweiz): Re-enable this when
        # https://github.com/dart-lang/sdk/issues/52121#issuecomment-1728534228
        # is addressed.
        # dart-channel: [stable, dev]
        shard: [0, 1, 2]
      fail-fast: false

    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: node --version

    - uses: dart-lang/setup-dart@v1.2
      with:
        sdk: ${{ matrix.dart-channel }}
    - run: dart --version

    - name: Configure Git
      run: |
        git config --global user.email "ci@local"
        git config --global user.name CI

    - run: dart pub get
    - run: dart run test -r expanded --total-shards 3 --shard-index ${{ matrix.shard }}

  browser-test:
    name: "Browser Tests | Dart ${{ matrix.dart-channel }}"

    strategy:
      matrix:
        dart-channel: [stable]
        # TODO(nweiz): Re-enable this when
        # https://github.com/dart-lang/sdk/issues/52121#issuecomment-1728534228
        # is addressed.
        # dart-channel: [stable, dev]
      fail-fast: false

    # Run browser tests on macos to avoid "No usable sandbox!" error on linux.
    # See https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
    runs-on: macos-latest
    steps:
    - uses: browser-actions/setup-chrome@v1
      id: setup-chrome
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: node --version

    - uses: dart-lang/setup-dart@v1.2
      with:
        sdk: ${{ matrix.dart-channel }}
    - run: dart --version

    - name: Configure Git
      run: |
        git config --global user.email "ci@local"
        git config --global user.name CI

    - run: dart pub get
      working-directory: ./browser_library_test

    - run: dart run grinder before-test
      working-directory: ./browser_library_test

    - run: ${{ steps.setup-chrome.outputs.chrome-path }} --version

    - run: dart run test --platform chrome --exclude-tags not-on-gh-actions
      working-directory: ./browser_library_test
      env:
        CHROME_EXECUTABLE: ${{ steps.setup-chrome.outputs.chrome-path }}

  format:
    name: "Code formatting"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1.2
    - run: dart --version
    - run: dart pub get
    - run: dart fix --apply
    - run: dart format .
    - run: git diff --exit-code
